name: kanakuu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.28.0 
  firebase_auth: ^4.19.0 
  cloud_firestore: ^4.17.0  
  firebase_storage: ^11.7.0 
  image_picker: ^1.1.0 
  shared_preferences: ^2.2.3 
  font_awesome_flutter: ^10.7.0 
  url_launcher: ^6.2.2 
  uuid: ^4.3.3 
  local_auth: ^2.2.0 
  intl: ^0.19.0 
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  share_plus: ^7.2.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Ahorra_logo.png